name: GCC Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build with Make
        run: |
          if [ -f Makefile ]; then
            make
          else
            echo "No Makefile found. Please add a Makefile or modify this step for your build process."
            exit 1
          fi
